version: '3.1'
services:
  proxy:
    depends_on:
      - app
    build:
      context: .
    volumes:
      - pictures:/var/pictures
    ports:
      - "80:80"
    networks:
      - loc

  app:
    depends_on:
      - db
    build: 
      context: medpoisk-server/
    environment:
      - SQLALCHEMY_DB_URL=postgresql://postgres:password@db/medpoisk
      - PICTURES_DIR=/var/pictures
      - PORT=7325
    volumes:
      - pictures:/var/pictures
    ports:
      - 7325:7325
    networks:
      - loc
    restart: always
  
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - psql-data:/var/lib/postgresql/data:rw
      - ./medpoisk-server/scripts/create_db.sql:/docker-entrypoint-initdb.d/1-create_db.sql:ro
      - ./medpoisk-server/scripts/inflate_db.sql:/docker-entrypoint-initdb.d/2-inflate_db.sql:ro
    networks:
      - loc
    restart: always

  # pgadmin:
  #   image: "dpage/pgadmin4:latest"
  #   depends_on:
  #     - db
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@domain.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   ports:
  #     - 5050:80
  #   restart: always

volumes:
  pictures:
  psql-data:
  dist:
    external: true

networks:
  loc:
  ext:
    driver: bridge